# Generated by Django 5.1.5 on 2025-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
