# Generated by Django 5.1.5 on 2025-06-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0002_alter_incidentstatus_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupactions',
            name='incident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='imsapp.incidentticket'),
        ),
        migrations.AlterField(
            model_name='improvementrecommendations',
            name='incident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='imsapp.incidentticket'),
        ),
    ]
