# Generated by Django 5.1.5 on 2025-06-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0003_alter_followupactions_incident_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentticket',
            name='requestor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.employee'),
        ),
    ]
