# Generated by Django 5.1.5 on 2025-06-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0004_alter_incidentticket_requestor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentticket',
            name='evidence',
        ),
        migrations.AlterField(
            model_name='incidentstatus',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inci_ticket', to='imsapp.incidentticket'),
        ),
    ]
