# Generated by Django 5.1.5 on 2025-06-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0005_remove_incidentticket_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='incident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inci_status', to='imsapp.incidentticket'),
        ),
    ]
